seed: 42
test_size: 0.2
embed_dim: 64
n_epochs: 100
lr: 0.01
weight_decay: 5e-4
n_clusters: 20
top_k: 10

data_path:
  ratings: "./data/ratings.csv"
  movies: "./data/movies.csv"
  links: "./data/links.csv"
  tags: "./data/tags.csv"

model_path:
  gcn: "./models/gcn_model.pth"
  kmeans: "./models/kmeans_model.pkl"
  
n_users: 610
n_items: 9742